on: [push]

name: Release

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      
      - name: Clone repository
        uses: actions/checkout@v2

      - name: List milestones
        run: |
          curl --request GET \
          --url https://api.github.com/repos/${{ github.repository }}/milestones?per_page=100 \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}'
