on: [push]

name: Release

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Close Milestone
        uses: WyriHaximus/github-action-close-milestone@0.1.0
        env:
          INPUT_NUMBER: 1
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
